field: 3f2bb7bd-de11-4ee6-bbab-87072c65f599 # Body
fieldLayouts:
  ebd9d4a9-016e-4ce1-957a-73e8435b207e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0b8b01fe-a1ec-47cf-8eab-abad9e8c53bf # Video Provider
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a03ad8e4-9ceb-4765-98c5-c242b7f23699
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6007bc23-db9d-4053-a881-a17dc5fa936f # Video ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0c499e5-7a56-4775-81cf-c68ed56bb6f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 53d0f18e-3cb4-4227-a49b-f1817c45883d # Caption
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f76e0f0-0fdf-42c5-a964-82ec94f11323
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 279ecbc7-ecc0-4842-89bc-98e1361563a4
        userCondition: null
fields:
  0b8b01fe-a1ec-47cf-8eab-abad9e8c53bf: # Video Provider
    columnSuffix: gxfqyujn
    contentColumnType: string(7)
    fieldGroup: null
    handle: mxVideoProvider
    instructions: null
    name: 'Video Provider'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Youtube
            -
              - value
              - youtube
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Vimeo
            -
              - value
              - vimeo
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  53d0f18e-3cb4-4227-a49b-f1817c45883d: # Caption
    columnSuffix: ijvmxbov
    contentColumnType: string(512)
    fieldGroup: null
    handle: mxVideoCaption
    instructions: null
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: 128
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6007bc23-db9d-4053-a881-a17dc5fa936f: # Video ID
    columnSuffix: bpqfqsbf
    contentColumnType: string(256)
    fieldGroup: null
    handle: mxVideoId
    instructions: 'The ID of the video in the URL. On Youtube, the ID for "https://www.youtube.com/watch?v=t-4U9fhjIGo" is "t-4U9fhjIGo". On Vimeo, the ID for "https://vimeo.com/874101998" is "874101998"'
    name: 'Video ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 64
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: mxblockVideo
name: Video
sortOrder: 3
