field: ef1fb6ef-4f7c-46f1-8c50-ad512f4112be # Skills
fieldLayouts:
  ff685ef5-7033-4d62-b881-2c3050b04152:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 70153458-713c-4f71-806c-a542381ee3d2 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 916f1e26-a5a2-4243-bf9b-31a997473382
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 516a237a-b730-463e-a03c-6b2bb2411511 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b6d218a-62cf-457f-a321-06a21b9b87d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 445835b9-ca02-413e-ab61-d07432e9372d
        userCondition: null
fields:
  516a237a-b730-463e-a03c-6b2bb2411511: # Text
    columnSuffix: houuujgx
    contentColumnType: string(1200)
    fieldGroup: null
    handle: mxSkillText
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: 300
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  70153458-713c-4f71-806c-a542381ee3d2: # Title
    columnSuffix: wapnfdtd
    contentColumnType: string(512)
    fieldGroup: null
    handle: mxSkillTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: 128
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: mxblockSkill
name: Skill
sortOrder: 1
