field: 3f2bb7bd-de11-4ee6-bbab-87072c65f599 # Body
fieldLayouts:
  4a797c60-dbe0-4360-a230-f1e4732f4ab7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a68a6aaa-1fce-40ff-9f32-26d305951bb1 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ffa0d6e-90d7-4815-861f-46f15b5b5c9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5926fc74-9319-47c2-b0a3-e4c2ee5e1ffb # Caption
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6501017-06c0-4773-8ba0-2025fa8a0247
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aa59d7dd-0873-491e-b177-d18264f4b3b7
        userCondition: null
fields:
  5926fc74-9319-47c2-b0a3-e4c2ee5e1ffb: # Caption
    columnSuffix: ugcyvmxs
    contentColumnType: string(512)
    fieldGroup: null
    handle: mxImageCaption
    instructions: null
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: 128
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a68a6aaa-1fce-40ff-9f32-26d305951bb1: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: mxImage
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:e3fc19a8-b337-4fb1-8276-52d33d5541af' # Projects Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:e3fc19a8-b337-4fb1-8276-52d33d5541af' # Projects Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: mxblockImage
name: Image
sortOrder: 2
