fieldLayouts:
  ee87b7c7-5f24-4466-8a7e-b23fc55bfe70:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d2f299c2-ff2e-45c8-a7bb-ec48ae2642fe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 12851af7-1740-45e8-ad06-bb257cfbed8f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 3f1a3ea3-19b9-4525-8405-d80f950530b6 # Projects Types
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
