fieldLayouts:
  4a3b30cc-6d6d-43bb-ae97-c7250bf71602:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 15ab0c06-24bd-402e-91e1-e9db33576231
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 409e18f1-2ea4-4fd3-801d-03ca6518b020 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00d81318-2734-47f8-8b7b-37e92ab875fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 12e2c4e6-a4ac-4173-a00c-d665dced72ca # Related Entry
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bca4e99d-3288-4190-bc84-7824c56fe75f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b36753f-e216-403d-85f5-455aefb0e18a
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: df2d68eb-2754-4b6e-896c-c06914209e5a # Main navigation
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{navLabel}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
