columnSuffix: extzsqxs
contentColumnType: string(64)
fieldGroup: 9814f4ed-6059-4e2f-b479-f79703a6b72f # Company
handle: companyAddressNumber
instructions: null
name: 'Address Street Number'
searchable: false
settings:
  byteLimit: null
  charLimit: 16
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
