columnSuffix: ykyhvugp
contentColumnType: string(256)
fieldGroup: 799b1430-d0f6-4c3c-aecd-579df0e77f17 # Homepage
handle: homeWedoTitle
instructions: null
name: 'What We Do Title'
searchable: false
settings:
  byteLimit: null
  charLimit: 64
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
