columnSuffix: null
contentColumnType: string
fieldGroup: 02386d47-d211-4898-81a8-11e1a7ca0b4f # Nav
handle: navEntry
instructions: null
name: 'Related Entry'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Link to a page'
  showSiteMenu: true
  sources:
    - 'custom:c2f98478-5cfe-4b80-bc61-d69fcbf7f93f'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
