columnSuffix: null
contentColumnType: string
fieldGroup: 2355c0f4-05c8-48bd-82a7-3960f4e16063 # Projects
handle: projectTypes
instructions: null
name: Types
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 10
  minRelations: 1
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Add type(s) of projects'
  showSiteMenu: true
  sources:
    - 'section:3f1a3ea3-19b9-4525-8405-d80f950530b6' # Projects Types
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
