columnSuffix: nojhqzak
contentColumnType: string(255)
fieldGroup: f26311f9-63aa-4363-b448-0b0e98547b4f # Social Media
handle: socialInstagramUrl
instructions: null
name: Instagram
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
