defaultPlacement: end
enableVersioning: true
handle: company
name: Company
propagationMethod: all
siteSettings:
  a345fca1-3553-4b32-a775-ea6d89626b13: # zodiak
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
