defaultPlacement: end
enableVersioning: true
handle: homePage
name: 'Home Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - preview
      -
        - urlFormat
        - /
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a345fca1-3553-4b32-a775-ea6d89626b13: # zodiak
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
