defaultPlacement: end
enableVersioning: true
handle: projectsPage
name: 'Projects Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - preview
      -
        - urlFormat
        - projects
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a345fca1-3553-4b32-a775-ea6d89626b13: # zodiak
    enabledByDefault: true
    hasUrls: true
    template: projects/_index.twig
    uriFormat: projects
type: single
