defaultPlacement: end
enableVersioning: true
handle: projects
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'preview project'
      -
        - urlFormat
        - 'projects/{slug}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a345fca1-3553-4b32-a775-ea6d89626b13: # zodiak
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry.twig
    uriFormat: 'projects/{slug}'
type: channel
